# Generated by Django 4.0.4 on 2022-05-11 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_clone', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
